# Dockerfile-frontend
# Stage 1 - the build process
FROM node:22-alpine

# Set working directory
WORKDIR /var/www/html

# Copy package.json and package-lock.json
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the app
RUN npm run dev

# # Stage 2 - the production environment
# FROM nginx:1.17.8-alpine

# # Copy build from Stage 1
# COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 3000

# # Start Nginx
# CMD ["nginx", "-g", "daemon off;"]